[project]
name = "genomics-model-zoo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "einops>=0.8.1",
    "pooch>=1.8.2",
    "torch>=2.7.1",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["setuptools>=70.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
regbench = ["data/tf_gammas.pt"]

[[tool.uv.index]]
name = "westlake"
url = "https://mirrors.westlake.edu.cn/pypi/simple"
default = true
